## Joshua Jones week 5 homework

#### 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

In [2]:
import numpy as np
import pandas as pd
import copy as cp


In [9]:
myarray  = np.array([[[1,2], [3,4], [5,6]],
                    [[7,8], [9,10], [11, 12]]])
print(myarray.shape)
print(myarray)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

In [10]:
myarray1 = np.linspace(0,20,6)
print(myarray1)

[ 0.  4.  8. 12. 16. 20.]


#### 9. Make a Deep Copy of the above array

In [11]:
#myarray1_copy = cp.deepcopy(myarray1[0]) #apparently this code made a deepcopy of my first number only, gonna comment out and rereun
myarray1_copy = cp.deepcopy(myarray1) 

print(myarray1_copy)

[ 0.  4.  8. 12. 16. 20.]


#### 10. Concatenate these 3 arrays into a new array named 'newArray'...

        ([[25, 16]])
        ([[11, 2], [13, 4]])
        ([[7, 81], [5, 6], [11, 12]])


In [12]:
myarray2 = np.array([ [25, 16] ] )
myarray3 = np.array([[11, 2], [13, 4]])
myarray4 = np.array([[7, 81], [5, 6], [11, 12]])

print(myarray2.shape)
print(myarray3.shape)
print(myarray4.shape)
print()

newArrayflat = np.concatenate((myarray2,myarray3,myarray4),axis=None)
print(newArrayflat)
print()

newArray = np.concatenate((myarray2,myarray3,myarray4),axis=0)
print(newArray)

(1, 2)
(2, 2)
(3, 2)

[25 16 11  2 13  4  7 81  5  6 11 12]

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


#### 11. Sort 'newArray' in order into 'sortedArray'

In [13]:
#print(newArray)
#print()

#newArray.sort(axis =0)
#print(newArray)
#print()

#sortedArray =newArray.sort(axis = 1)
#print(sortedArray)

sortedArray = np.sort(newArray, axis = 1)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


#### 12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

In [14]:
testarray = myarray.reshape(4,3,1)
testarray


array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [16]:
var1,var2,var3,var4 = testarray

print('var1:', var1)
print('var2:', var2)
print('var3:', var3)
print('var4:', var4)

var1: [[1]
 [2]
 [3]]
var2: [[4]
 [5]
 [6]]
var3: [[7]
 [8]
 [9]]
var4: [[10]
 [11]
 [12]]


#### 13. Combined and sort the following arrays into one called 'comboArray' ...
- one = ([10, 11, 12, 13, 14, 15, 16, 17])
- two = ([20, 21, 22, 23, 24, 25, 26, 27])
- three = ([ 0, 1, 2, 3, 4, 5, 6, 7])



In [250]:
jarray1= np.array([10, 11, 12, 13, 14, 15, 16, 17])
jarray2= np.array([20, 21, 22, 23, 24, 25, 26, 27])
jarray3= np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

print(jarray1.shape)
print(jarray2.shape)
print(jarray3.shape)
print()

comboArray = np.concatenate((jarray1,jarray2,jarray3), axis = 0)
print(comboArray)

comboArray = np.concatenate((jarray1,jarray2,jarray3), axis = None)
comboArray

(8,)
(8,)
(8,)

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]


array([10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27,  0,
        1,  2,  3,  4,  5,  6,  7])

#### 14. Take 'comboArray' and perform the following slicing activities:

- print sec1 - the 2nd element
- print sec2 - all elements from the 3rd element to the last
- print sec3 - all elements from the 4th to the 14th elements
- print sec4 - the last 6 elements
- print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
- print sec6 - from #20 every even element to the end
- print sec7 - from the last element moving forward, every 5th element.

In [382]:
print('sec1 - the 2nd element')
print(comboArray[1], '\n')
print('sec2 - all elements from the 3rd element to the last')
print(comboArray[2:], '\n')
print('sec3 - all elements from the 4th to the 14th elements')
print(comboArray[3:15], '\n')
print('sec4 - the last 6 elements')
print(comboArray[-6:], '\n')
#print(comboArray.size, '\n')
print('sec4 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.')
print(comboArray[-24:-9], '\n')
print('sec6 - from #20 every even element to the end')
print(comboArray[20:24:2], '\n')
print('sec7 - from the last element moving forward, every 5th element.')
print(comboArray[-1:-24:-5], '\n')



#print(np.where(comboArray == 0)), couldn't figure this code out

sec1 - the 2nd element
11 

sec2 - all elements from the 3rd element to the last
[12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7] 

sec3 - all elements from the 4th to the 14th elements
[13 14 15 16 17 20 21 22 23 24 25 26] 

sec4 - the last 6 elements
[2 3 4 5 6 7] 

sec4 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26] 

sec6 - from #20 every even element to the end
[4 6] 

sec7 - from the last element moving forward, every 5th element.
[ 7  2 25 20 13] 



#### 15. Using Series, create a DataFrame that looks like this:



| Ingredients |	Quantity |	Unit|
|-------------|----------|------|
| Flour	      | 4	     | cups |
| Milk	      | 1	     | cup  | 
| Eggs	      | 2	     | large|
| Spam	      | 1	     | can  |

In [5]:
import pandas as pd

In [15]:
Ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name ='Ingredients')
Quantity = pd.Series([4,1,2,1], name='Quantity')
Units = pd.Series(['cups','cup','large','can'], name='Unit')
df = pd.concat([Ingredients,Quantity,Units], axis=1)
df


Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

#### 16. Take this data and create a DataFrame named studentData

    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

In [28]:
studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

df = pd.DataFrame(studentData)
df

Name  Height Qualification  Address  Age        Pets           Sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

#### 17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [ ]:
desserts = ['ice cream','Cashew Fudge', 'waffels', 'Carrot Halwa']
df.insert(7, 'desserts', desserts)


In [52]:
df

Name  Height Qualification  Address  Age        Pets           Sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       desserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

#### 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"



In [61]:
df.sort_values(by = ['Name', 'Address'], ascending = True, inplace = True)
df

Name  Height Qualification  Address  Age        Pets           Sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       desserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

#### 19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

    df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

In [5]:
from pathlib import Path

In [8]:
df1 = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
#df1.to_csv('cows_and_goats.csv') #sends to working folder

filepath = Path(r'C:\Users\artif\code\SavvyCoders\Activities\cows_and_goats.csv') # I saw this in the docs and wanted to see if i could get it to work, it worked just fine
df1.to_csv(filepath)

#### 20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [12]:
vegetables = {'name': ['carrot', 'celery', 'corn', 'radish'],
    'color': ['orange', 'green', 'yellow', 'white'],
    'rootcrop': [True, False, False, True],
    'weather_preference': ['both', 'cool', 'hot', 'cool'],
    }

 
df2 = pd.DataFrame(vegetables)
df2.to_csv('vegetables.csv')



In [18]:
df2

name   color  rootcrop weather_preference
0  carrot  orange      True               both
1  celery   green     False               cool
2    corn  yellow     False                hot
3  radish   white      True               cool

In [22]:
df3 = pd.read_csv('vegetables.csv')
# print(titanic_data.head())


df3

Unnamed: 0    name   color  rootcrop weather_preference
0           0  carrot  orange      True               both
1           1  celery   green     False               cool
2           2    corn  yellow     False                hot
3           3  radish   white      True               cool

In [23]:
df3.drop(['Unnamed: 0'],axis= 1, inplace= True)
df3

name   color  rootcrop weather_preference
0  carrot  orange      True               both
1  celery   green     False               cool
2    corn  yellow     False                hot
3  radish   white      True               cool

In [25]:
new_row = {'name': 'spinach', 'color': 'green', 'rootcrop': False, 'weather_preference': 'cool'}
df3.loc[len(df3)] = new_row
df3

name   color  rootcrop weather_preference
0   carrot  orange      True               both
1   celery   green     False               cool
2     corn  yellow     False                hot
3   radish   white      True               cool
4  spinach   green     False               cool

In [26]:
df3.to_csv('vegetables2.csv', index=False )